---
title: "project_part_1"
author: "Annie Zhu"
date: "2023-01-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
```

## Data Cleaning

Here I will be adding an extra row for easier understanding of what every value represents. More specifically, I am taking the description of what each attribute means from the repository description online and converting it into variable names for each column.

```{r blogset}
data <- read_csv("./BlogFeedback/blogData_train.csv", col_names = FALSE, show_col_types = FALSE)
basic_attributes <- c("total_before", "24hr_before", "48hr_to_24hr", "first_24hr", "change_between_two_days")
prefix <- c("avg", "sd", "min", "max", "med")
suffix <- c("comments", "links")
for (i in 1:5){
  for (j in 1:2) {
    for (k in 1:5) {
      index = 10 * (i-1) + 5 * (j-1) + k
      colnames(data)[index] <- paste(prefix[k], basic_attributes[i], suffix[j], sep = "_")
    }
  }
}

for (i in 1:5){
  for (j in 1:2) {
    index = 50 + i + 5 * (j-1)
    colnames(data)[index] <- paste(basic_attributes[i], suffix[j], sep = "_")
  }
}

colnames(data)[61] <- "time_length"
colnames(data)[62] <- "post_length"
for (i in 1: 200){
  index = toString(i)
  colnames(data)[i + 62] <- paste("freq_word_feature_", index, sep = "")
}

days <- c("mon", "tues", "wed", "thurs", "fri", "sat", "sun")
for (i in 1:7) {
  colnames(data)[i + 262] <- paste("basetime", days[i], sep = "_")
}
for (i in 1:7) {
  colnames(data)[i + 269] <- paste("publication", days[i], sep = "_")
}

colnames(data)[277] <- "parent_pages_count"
colnames(data)[278] <- "min_parent_pages_comments"
colnames(data)[279] <- "max_parent_pages_comments"
colnames(data)[280] <- "avg_parent_pages_comments"
colnames(data)[281] <- "24hr_after_comments"
print(data)


```

